CREATE TABLE ACT_GE_PROPERTY
(
    NAME_  NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    VALUE_ NVARCHAR2(300),
    REV_   NUMBER
)
    /

CREATE TABLE ACT_GE_BYTEARRAY
(
    ID_                NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_               NUMBER,
    NAME_              NVARCHAR2(255),
    DEPLOYMENT_ID_     NVARCHAR2(64),
    BYTES_             BLOB,
    GENERATED_         NUMBER(1)
        CHECK (GENERATED_ IN (1, 0)),
    TENANT_ID_         NVARCHAR2(64),
    TYPE_              NUMBER,
    CREATE_TIME_       TIMESTAMP(6),
    ROOT_PROC_INST_ID_ VARCHAR2(64),
    REMOVAL_TIME_      TIMESTAMP(6)
)
    /

CREATE
INDEX ACT_IDX_BYTEARRAY_NAME
  ON ACT_GE_BYTEARRAY (NAME_)
/

CREATE
INDEX ACT_IDX_BYTEAR_DEPL
  ON ACT_GE_BYTEARRAY (DEPLOYMENT_ID_)
/

CREATE
INDEX ACT_IDX_BYTEARRAY_ROOT_PI
  ON ACT_GE_BYTEARRAY (ROOT_PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_BYTEARRAY_RM_TIME
  ON ACT_GE_BYTEARRAY (REMOVAL_TIME_)
/

CREATE TABLE ACT_RE_DEPLOYMENT
(
    ID_          NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    NAME_        NVARCHAR2(255),
    DEPLOY_TIME_ TIMESTAMP(6),
    SOURCE_      NVARCHAR2(255),
    TENANT_ID_   NVARCHAR2(64)
)
    /

CREATE
INDEX ACT_IDX_DEPLOYMENT_NAME
  ON ACT_RE_DEPLOYMENT (NAME_)
/

CREATE
INDEX ACT_IDX_DEPLOYMENT_TENANT_ID
  ON ACT_RE_DEPLOYMENT (TENANT_ID_, 0)
/

ALTER TABLE ACT_GE_BYTEARRAY
    ADD CONSTRAINT ACT_FK_BYTEARR_DEPL
        FOREIGN KEY (DEPLOYMENT_ID_) REFERENCES ACT_RE_DEPLOYMENT /

CREATE TABLE ACT_RU_EXECUTION
(
    ID_                NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_               NUMBER,
    ROOT_PROC_INST_ID_ NVARCHAR2(64),
    PROC_INST_ID_      NVARCHAR2(64)
        CONSTRAINT ACT_FK_EXE_PROCINST
        REFERENCES ACT_RU_EXECUTION,
    BUSINESS_KEY_      NVARCHAR2(255),
    PARENT_ID_         NVARCHAR2(64)
        CONSTRAINT ACT_FK_EXE_PARENT
        REFERENCES ACT_RU_EXECUTION,
    PROC_DEF_ID_       NVARCHAR2(64),
    SUPER_EXEC_        NVARCHAR2(64)
        CONSTRAINT ACT_FK_EXE_SUPER
        REFERENCES ACT_RU_EXECUTION,
    SUPER_CASE_EXEC_   NVARCHAR2(64),
    CASE_INST_ID_      NVARCHAR2(64),
    ACT_ID_            NVARCHAR2(255),
    ACT_INST_ID_       NVARCHAR2(64),
    IS_ACTIVE_         NUMBER(1)
        CHECK (IS_ACTIVE_ IN (1, 0)),
    IS_CONCURRENT_     NUMBER(1)
        CHECK (IS_CONCURRENT_ IN (1, 0)),
    IS_SCOPE_          NUMBER(1)
        CHECK (IS_SCOPE_ IN (1, 0)),
    IS_EVENT_SCOPE_    NUMBER(1)
        CHECK (IS_EVENT_SCOPE_ IN (1, 0)),
    SUSPENSION_STATE_  NUMBER,
    CACHED_ENT_STATE_  NUMBER,
    SEQUENCE_COUNTER_  NUMBER(19),
    TENANT_ID_         NVARCHAR2(64)
)
    /

CREATE
INDEX ACT_IDX_EXE_ROOT_PROCINST
  ON ACT_RU_EXECUTION (ROOT_PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_EXE_PROCINST
  ON ACT_RU_EXECUTION (PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_EXEC_BUSKEY
  ON ACT_RU_EXECUTION (BUSINESS_KEY_)
/

CREATE
INDEX ACT_IDX_EXE_PARENT
  ON ACT_RU_EXECUTION (PARENT_ID_)
/

CREATE
INDEX ACT_IDX_EXE_PROCDEF
  ON ACT_RU_EXECUTION (PROC_DEF_ID_)
/

CREATE
INDEX ACT_IDX_EXE_SUPER
  ON ACT_RU_EXECUTION (SUPER_EXEC_)
/

CREATE
INDEX ACT_IDX_EXEC_TENANT_ID
  ON ACT_RU_EXECUTION (TENANT_ID_, 0)
/

CREATE TABLE ACT_RU_JOB
(
    ID_                  NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_                 NUMBER,
    TYPE_                NVARCHAR2(255) NOT NULL,
    LOCK_EXP_TIME_       TIMESTAMP(6),
    LOCK_OWNER_          NVARCHAR2(255),
    EXCLUSIVE_           NUMBER(1)
        CHECK (EXCLUSIVE_ IN (1, 0)),
    EXECUTION_ID_        NVARCHAR2(64),
    PROCESS_INSTANCE_ID_ NVARCHAR2(64),
    PROCESS_DEF_ID_      NVARCHAR2(64),
    PROCESS_DEF_KEY_     NVARCHAR2(255),
    RETRIES_             NUMBER,
    EXCEPTION_STACK_ID_  NVARCHAR2(64)
        CONSTRAINT ACT_FK_JOB_EXCEPTION
        REFERENCES ACT_GE_BYTEARRAY,
    EXCEPTION_MSG_       NVARCHAR2(2000),
    DUEDATE_             TIMESTAMP(6),
    REPEAT_              NVARCHAR2(255),
    HANDLER_TYPE_        NVARCHAR2(255),
    HANDLER_CFG_         NVARCHAR2(2000),
    DEPLOYMENT_ID_       NVARCHAR2(64),
    SUSPENSION_STATE_    NUMBER DEFAULT 1 NOT NULL,
    JOB_DEF_ID_          NVARCHAR2(64),
    PRIORITY_            NUMBER(19) DEFAULT 0 NOT NULL,
    SEQUENCE_COUNTER_    NUMBER(19),
    TENANT_ID_           NVARCHAR2(64),
    CREATE_TIME_         TIMESTAMP(6)
)
    /

CREATE
INDEX ACT_IDX_JOB_EXECUTION_ID
  ON ACT_RU_JOB (EXECUTION_ID_)
/

CREATE
INDEX ACT_IDX_JOB_PROCINST
  ON ACT_RU_JOB (PROCESS_INSTANCE_ID_)
/

CREATE
INDEX ACT_IDX_JOB_EXCEPTION
  ON ACT_RU_JOB (EXCEPTION_STACK_ID_)
/

CREATE
INDEX ACT_IDX_JOB_HANDLER
  ON ACT_RU_JOB (HANDLER_TYPE_, HANDLER_CFG_)
/

CREATE
INDEX ACT_IDX_JOB_HANDLER_TYPE
  ON ACT_RU_JOB (HANDLER_TYPE_)
/

CREATE
INDEX ACT_IDX_JOB_JOB_DEF_ID
  ON ACT_RU_JOB (JOB_DEF_ID_)
/

CREATE
INDEX ACT_IDX_JOB_TENANT_ID
  ON ACT_RU_JOB (TENANT_ID_, 0)
/

CREATE TABLE ACT_RU_JOBDEF
(
    ID_                NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_               NUMBER,
    PROC_DEF_ID_       NVARCHAR2(64),
    PROC_DEF_KEY_      NVARCHAR2(255),
    ACT_ID_            NVARCHAR2(255),
    JOB_TYPE_          NVARCHAR2(255) NOT NULL,
    JOB_CONFIGURATION_ NVARCHAR2(255),
    SUSPENSION_STATE_  NUMBER,
    JOB_PRIORITY_      NUMBER(19),
    TENANT_ID_         NVARCHAR2(64)
)
    /

CREATE
INDEX ACT_IDX_JOBDEF_PROC_DEF_ID
  ON ACT_RU_JOBDEF (PROC_DEF_ID_)
/

CREATE
INDEX ACT_IDX_JOBDEF_TENANT_ID
  ON ACT_RU_JOBDEF (TENANT_ID_, 0)
/

CREATE TABLE ACT_RE_PROCDEF
(
    ID_                 NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_                NUMBER,
    CATEGORY_           NVARCHAR2(255),
    NAME_               NVARCHAR2(255),
    KEY_                NVARCHAR2(255) NOT NULL,
    VERSION_            NUMBER NOT NULL,
    DEPLOYMENT_ID_      NVARCHAR2(64),
    RESOURCE_NAME_      NVARCHAR2(2000),
    DGRM_RESOURCE_NAME_ NVARCHAR2(2000),
    HAS_START_FORM_KEY_ NUMBER(1)
        CHECK (HAS_START_FORM_KEY_ IN (1, 0)),
    SUSPENSION_STATE_   NUMBER,
    TENANT_ID_          NVARCHAR2(64),
    VERSION_TAG_        NVARCHAR2(64),
    HISTORY_TTL_        NUMBER,
    STARTABLE_          NUMBER(1) DEFAULT 1 NOT NULL
        CHECK (STARTABLE_ IN (1, 0))
)
    /

CREATE
INDEX ACT_IDX_PROCDEF_DEPLOYMENT_ID
  ON ACT_RE_PROCDEF (DEPLOYMENT_ID_)
/

CREATE
INDEX ACT_IDX_PROCDEF_TENANT_ID
  ON ACT_RE_PROCDEF (TENANT_ID_, 0)
/

CREATE
INDEX ACT_IDX_PROCDEF_VER_TAG
  ON ACT_RE_PROCDEF (VERSION_TAG_)
/

ALTER TABLE ACT_RU_EXECUTION
    ADD CONSTRAINT ACT_FK_EXE_PROCDEF
        FOREIGN KEY (PROC_DEF_ID_) REFERENCES ACT_RE_PROCDEF /

CREATE TABLE ACT_RU_TASK
(
    ID_                NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_               NUMBER,
    EXECUTION_ID_      NVARCHAR2(64)
        CONSTRAINT ACT_FK_TASK_EXE
        REFERENCES ACT_RU_EXECUTION,
    PROC_INST_ID_      NVARCHAR2(64)
        CONSTRAINT ACT_FK_TASK_PROCINST
        REFERENCES ACT_RU_EXECUTION,
    PROC_DEF_ID_       NVARCHAR2(64)
        CONSTRAINT ACT_FK_TASK_PROCDEF
        REFERENCES ACT_RE_PROCDEF,
    CASE_EXECUTION_ID_ NVARCHAR2(64),
    CASE_INST_ID_      NVARCHAR2(64),
    CASE_DEF_ID_       NVARCHAR2(64),
    NAME_              NVARCHAR2(255),
    PARENT_TASK_ID_    NVARCHAR2(64),
    DESCRIPTION_       NVARCHAR2(2000),
    TASK_DEF_KEY_      NVARCHAR2(255),
    OWNER_             NVARCHAR2(255),
    ASSIGNEE_          NVARCHAR2(255),
    DELEGATION_        NVARCHAR2(64),
    PRIORITY_          NUMBER,
    CREATE_TIME_       TIMESTAMP(6),
    DUE_DATE_          TIMESTAMP(6),
    FOLLOW_UP_DATE_    TIMESTAMP(6),
    SUSPENSION_STATE_  NUMBER,
    TENANT_ID_         NVARCHAR2(64)
)
    /

CREATE
INDEX ACT_IDX_TASK_EXEC
  ON ACT_RU_TASK (EXECUTION_ID_)
/

CREATE
INDEX ACT_IDX_TASK_PROCINST
  ON ACT_RU_TASK (PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_TASK_PROCDEF
  ON ACT_RU_TASK (PROC_DEF_ID_)
/

CREATE
INDEX ACT_IDX_TASK_CASE_EXEC
  ON ACT_RU_TASK (CASE_EXECUTION_ID_)
/

CREATE
INDEX ACT_IDX_TASK_CASE_DEF_ID
  ON ACT_RU_TASK (CASE_DEF_ID_)
/

CREATE
INDEX ACT_IDX_TASK_ASSIGNEE
  ON ACT_RU_TASK (ASSIGNEE_)
/

CREATE
INDEX ACT_IDX_TASK_CREATE
  ON ACT_RU_TASK (CREATE_TIME_)
/

CREATE
INDEX ACT_IDX_TASK_TENANT_ID
  ON ACT_RU_TASK (TENANT_ID_, 0)
/

CREATE TABLE ACT_RU_IDENTITYLINK
(
    ID_          NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_         NUMBER,
    GROUP_ID_    NVARCHAR2(255),
    TYPE_        NVARCHAR2(255),
    USER_ID_     NVARCHAR2(255),
    TASK_ID_     NVARCHAR2(64)
        CONSTRAINT ACT_FK_TSKASS_TASK
        REFERENCES ACT_RU_TASK,
    PROC_DEF_ID_ NVARCHAR2(64)
        CONSTRAINT ACT_FK_ATHRZ_PROCEDEF
        REFERENCES ACT_RE_PROCDEF,
    TENANT_ID_   NVARCHAR2(64)
)
    /

CREATE
INDEX ACT_IDX_IDENT_LNK_GROUP
  ON ACT_RU_IDENTITYLINK (GROUP_ID_)
/

CREATE
INDEX ACT_IDX_IDENT_LNK_USER
  ON ACT_RU_IDENTITYLINK (USER_ID_)
/

CREATE
INDEX ACT_IDX_TSKASS_TASK
  ON ACT_RU_IDENTITYLINK (TASK_ID_)
/

CREATE
INDEX ACT_IDX_ATHRZ_PROCEDEF
  ON ACT_RU_IDENTITYLINK (PROC_DEF_ID_)
/

CREATE TABLE ACT_RU_VARIABLE
(
    ID_                  NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_                 NUMBER,
    TYPE_                NVARCHAR2(255) NOT NULL,
    NAME_                NVARCHAR2(255) NOT NULL,
    EXECUTION_ID_        NVARCHAR2(64)
        CONSTRAINT ACT_FK_VAR_EXE
        REFERENCES ACT_RU_EXECUTION,
    PROC_INST_ID_        NVARCHAR2(64)
        CONSTRAINT ACT_FK_VAR_PROCINST
        REFERENCES ACT_RU_EXECUTION,
    CASE_EXECUTION_ID_   NVARCHAR2(64),
    CASE_INST_ID_        NVARCHAR2(64),
    TASK_ID_             NVARCHAR2(64),
    BYTEARRAY_ID_        NVARCHAR2(64)
        CONSTRAINT ACT_FK_VAR_BYTEARRAY
        REFERENCES ACT_GE_BYTEARRAY,
    DOUBLE_              NUMBER(*, 10),
    LONG_                NUMBER(19),
    TEXT_                NVARCHAR2(2000),
    TEXT2_               NVARCHAR2(2000),
    VAR_SCOPE_           NVARCHAR2(64) NOT NULL,
    SEQUENCE_COUNTER_    NUMBER(19),
    IS_CONCURRENT_LOCAL_ NUMBER(1)
        CHECK (IS_CONCURRENT_LOCAL_ IN (1, 0)),
    TENANT_ID_           NVARCHAR2(64),
    CONSTRAINT ACT_UNIQ_VARIABLE
        UNIQUE (VAR_SCOPE_, NAME_)
)
    /

CREATE
INDEX ACT_IDX_VAR_EXE
  ON ACT_RU_VARIABLE (EXECUTION_ID_)
/

CREATE
INDEX ACT_IDX_VAR_PROCINST
  ON ACT_RU_VARIABLE (PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_VAR_CASE_EXE
  ON ACT_RU_VARIABLE (CASE_EXECUTION_ID_)
/

CREATE
INDEX ACT_IDX_VAR_CASE_INST_ID
  ON ACT_RU_VARIABLE (CASE_INST_ID_)
/

CREATE
INDEX ACT_IDX_VARIABLE_TASK_ID
  ON ACT_RU_VARIABLE (TASK_ID_)
/

CREATE
INDEX ACT_IDX_VAR_BYTEARRAY
  ON ACT_RU_VARIABLE (BYTEARRAY_ID_)
/

CREATE
INDEX ACT_IDX_VARIABLE_TENANT_ID
  ON ACT_RU_VARIABLE (TENANT_ID_, 0)
/

CREATE TABLE ACT_RU_EVENT_SUBSCR
(
    ID_            NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_           NUMBER,
    EVENT_TYPE_    NVARCHAR2(255) NOT NULL,
    EVENT_NAME_    NVARCHAR2(255),
    EXECUTION_ID_  NVARCHAR2(64)
        CONSTRAINT ACT_FK_EVENT_EXEC
        REFERENCES ACT_RU_EXECUTION,
    PROC_INST_ID_  NVARCHAR2(64),
    ACTIVITY_ID_   NVARCHAR2(255),
    CONFIGURATION_ NVARCHAR2(255),
    CREATED_       TIMESTAMP(6) NOT NULL,
    TENANT_ID_     NVARCHAR2(64)
)
    /

CREATE
INDEX ACT_IDX_EVENT_SUBSCR_EVT_NAME
  ON ACT_RU_EVENT_SUBSCR (EVENT_NAME_)
/

CREATE
INDEX ACT_IDX_EVENT_SUBSCR
  ON ACT_RU_EVENT_SUBSCR (EXECUTION_ID_)
/

CREATE
INDEX ACT_IDX_EVENT_SUBSCR_CONFIG_
  ON ACT_RU_EVENT_SUBSCR (CONFIGURATION_)
/

CREATE
INDEX ACT_IDX_EVENT_SUBSCR_TENANT_ID
  ON ACT_RU_EVENT_SUBSCR (TENANT_ID_, 0)
/

CREATE TABLE ACT_RU_INCIDENT
(
    ID_                     NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_                    NUMBER       NOT NULL,
    INCIDENT_TIMESTAMP_     TIMESTAMP(6) NOT NULL,
    INCIDENT_MSG_           NVARCHAR2(2000),
    INCIDENT_TYPE_          NVARCHAR2(255) NOT NULL,
    EXECUTION_ID_           NVARCHAR2(64)
        CONSTRAINT ACT_FK_INC_EXE
        REFERENCES ACT_RU_EXECUTION,
    ACTIVITY_ID_            NVARCHAR2(255),
    PROC_INST_ID_           NVARCHAR2(64)
        CONSTRAINT ACT_FK_INC_PROCINST
        REFERENCES ACT_RU_EXECUTION,
    PROC_DEF_ID_            NVARCHAR2(64)
        CONSTRAINT ACT_FK_INC_PROCDEF
        REFERENCES ACT_RE_PROCDEF,
    CAUSE_INCIDENT_ID_      NVARCHAR2(64)
        CONSTRAINT ACT_FK_INC_CAUSE
        REFERENCES ACT_RU_INCIDENT,
    ROOT_CAUSE_INCIDENT_ID_ NVARCHAR2(64)
        CONSTRAINT ACT_FK_INC_RCAUSE
        REFERENCES ACT_RU_INCIDENT,
    CONFIGURATION_          NVARCHAR2(255),
    TENANT_ID_              NVARCHAR2(64),
    JOB_DEF_ID_             NVARCHAR2(64)
        CONSTRAINT ACT_FK_INC_JOB_DEF
        REFERENCES ACT_RU_JOBDEF
)
    /

CREATE
INDEX ACT_IDX_INC_EXID
  ON ACT_RU_INCIDENT (EXECUTION_ID_)
/

CREATE
INDEX ACT_IDX_INC_PROCINSTID
  ON ACT_RU_INCIDENT (PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_INC_PROCDEFID
  ON ACT_RU_INCIDENT (PROC_DEF_ID_)
/

CREATE
INDEX ACT_IDX_INC_CAUSEINCID
  ON ACT_RU_INCIDENT (CAUSE_INCIDENT_ID_)
/

CREATE
INDEX ACT_IDX_INC_ROOTCAUSEINCID
  ON ACT_RU_INCIDENT (ROOT_CAUSE_INCIDENT_ID_)
/

CREATE
INDEX ACT_IDX_INC_CONFIGURATION
  ON ACT_RU_INCIDENT (CONFIGURATION_)
/

CREATE
INDEX ACT_IDX_INC_TENANT_ID
  ON ACT_RU_INCIDENT (TENANT_ID_, 0)
/

CREATE
INDEX ACT_IDX_INC_JOB_DEF
  ON ACT_RU_INCIDENT (JOB_DEF_ID_)
/

CREATE TABLE ACT_RU_AUTHORIZATION
(
    ID_            NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_           NUMBER NOT NULL,
    TYPE_          NUMBER NOT NULL,
    GROUP_ID_      NVARCHAR2(255),
    USER_ID_       NVARCHAR2(255),
    RESOURCE_TYPE_ NUMBER NOT NULL,
    RESOURCE_ID_   NVARCHAR2(255),
    PERMS_         NUMBER
)
    /

CREATE
UNIQUE INDEX ACT_UNIQ_AUTH_GROUP
  ON ACT_RU_AUTHORIZATION (CASE WHEN "GROUP_ID_" IS NULL
    THEN NULL
                           ELSE "TYPE_" END, CASE WHEN "GROUP_ID_" IS NULL
    THEN NULL
                                             ELSE "RESOURCE_TYPE_" END, CASE WHEN "GROUP_ID_" IS NULL
    THEN NULL
                                                                        ELSE "RESOURCE_ID_" END, CASE WHEN "GROUP_ID_"
                                                                                                           IS NULL
    THEN NULL
                                                                                                 ELSE "GROUP_ID_" END)
/

CREATE
UNIQUE INDEX ACT_UNIQ_AUTH_USER
  ON ACT_RU_AUTHORIZATION (CASE WHEN "USER_ID_" IS NULL
    THEN NULL
                           ELSE "TYPE_" END, CASE WHEN "USER_ID_" IS NULL
    THEN NULL
                                             ELSE "RESOURCE_TYPE_" END, CASE WHEN "USER_ID_" IS NULL
    THEN NULL
                                                                        ELSE "RESOURCE_ID_" END, CASE WHEN "USER_ID_" IS
                                                                                                           NULL
    THEN NULL
                                                                                                 ELSE "USER_ID_" END)
/

CREATE
INDEX ACT_IDX_AUTH_GROUP_ID
  ON ACT_RU_AUTHORIZATION (GROUP_ID_)
/

CREATE
INDEX ACT_IDX_AUTH_RESOURCE_ID
  ON ACT_RU_AUTHORIZATION (RESOURCE_ID_)
/

CREATE TABLE ACT_RU_FILTER
(
    ID_            NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_           NUMBER NOT NULL,
    RESOURCE_TYPE_ NVARCHAR2(255) NOT NULL,
    NAME_          NVARCHAR2(255) NOT NULL,
    OWNER_         NVARCHAR2(255),
    QUERY_         NCLOB  NOT NULL,
    PROPERTIES_    NCLOB
)
    /

CREATE TABLE ACT_RU_METER_LOG
(
    ID_           NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    NAME_         NVARCHAR2(64) NOT NULL,
    REPORTER_     NVARCHAR2(255),
    VALUE_        NUMBER(19),
    TIMESTAMP_    TIMESTAMP(6),
    MILLISECONDS_ NUMBER(19) DEFAULT 0
)
    /

CREATE
INDEX ACT_IDX_METER_LOG_REPORT
  ON ACT_RU_METER_LOG (NAME_, REPORTER_, MILLISECONDS_)
/

CREATE
INDEX ACT_IDX_METER_LOG
  ON ACT_RU_METER_LOG (NAME_, TIMESTAMP_)
/

CREATE
INDEX ACT_IDX_METER_LOG_NAME_MS
  ON ACT_RU_METER_LOG (NAME_, MILLISECONDS_)
/

CREATE
INDEX ACT_IDX_METER_LOG_TIME
  ON ACT_RU_METER_LOG (TIMESTAMP_)
/

CREATE
INDEX ACT_IDX_METER_LOG_MS
  ON ACT_RU_METER_LOG (MILLISECONDS_)
/

CREATE TABLE ACT_RU_EXT_TASK
(
    ID_               NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_              NUMBER NOT NULL,
    WORKER_ID_        NVARCHAR2(255),
    TOPIC_NAME_       NVARCHAR2(255),
    RETRIES_          NUMBER,
    ERROR_MSG_        NVARCHAR2(2000),
    ERROR_DETAILS_ID_ NVARCHAR2(64)
        CONSTRAINT ACT_FK_EXT_TASK_ERROR_DETAILS
        REFERENCES ACT_GE_BYTEARRAY,
    LOCK_EXP_TIME_    TIMESTAMP(6),
    SUSPENSION_STATE_ NUMBER,
    EXECUTION_ID_     NVARCHAR2(64)
        CONSTRAINT ACT_FK_EXT_TASK_EXE
        REFERENCES ACT_RU_EXECUTION,
    PROC_INST_ID_     NVARCHAR2(64),
    PROC_DEF_ID_      NVARCHAR2(64),
    PROC_DEF_KEY_     NVARCHAR2(255),
    ACT_ID_           NVARCHAR2(255),
    ACT_INST_ID_      NVARCHAR2(64),
    TENANT_ID_        NVARCHAR2(64),
    PRIORITY_         NUMBER(19) DEFAULT 0 NOT NULL
)
    /

CREATE
INDEX ACT_IDX_EXT_TASK_TOPIC
  ON ACT_RU_EXT_TASK (TOPIC_NAME_)
/

CREATE
INDEX ACT_IDX_EXT_TASK_ERR_DETAILS
  ON ACT_RU_EXT_TASK (ERROR_DETAILS_ID_)
/

CREATE
INDEX ACT_IDX_EXT_TASK_EXEC
  ON ACT_RU_EXT_TASK (EXECUTION_ID_)
/

CREATE
INDEX ACT_IDX_EXT_TASK_TENANT_ID
  ON ACT_RU_EXT_TASK (TENANT_ID_, 0)
/

CREATE
INDEX ACT_IDX_EXT_TASK_PRIORITY
  ON ACT_RU_EXT_TASK (PRIORITY_)
/

CREATE TABLE ACT_RU_BATCH
(
    ID_                  NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_                 NUMBER NOT NULL,
    TYPE_                NVARCHAR2(255),
    TOTAL_JOBS_          NUMBER,
    JOBS_CREATED_        NUMBER,
    JOBS_PER_SEED_       NUMBER,
    INVOCATIONS_PER_JOB_ NUMBER,
    SEED_JOB_DEF_ID_     NVARCHAR2(64)
        CONSTRAINT ACT_FK_BATCH_SEED_JOB_DEF
        REFERENCES ACT_RU_JOBDEF,
    BATCH_JOB_DEF_ID_    NVARCHAR2(64)
        CONSTRAINT ACT_FK_BATCH_JOB_DEF
        REFERENCES ACT_RU_JOBDEF,
    MONITOR_JOB_DEF_ID_  NVARCHAR2(64)
        CONSTRAINT ACT_FK_BATCH_MONITOR_JOB_DEF
        REFERENCES ACT_RU_JOBDEF,
    SUSPENSION_STATE_    NUMBER,
    CONFIGURATION_       NVARCHAR2(255),
    TENANT_ID_           NVARCHAR2(64),
    CREATE_USER_ID_      NVARCHAR2(255)
)
    /

CREATE
INDEX ACT_IDX_BATCH_SEED_JOB_DEF
  ON ACT_RU_BATCH (SEED_JOB_DEF_ID_)
/

CREATE
INDEX ACT_IDX_BATCH_JOB_DEF
  ON ACT_RU_BATCH (BATCH_JOB_DEF_ID_)
/

CREATE
INDEX ACT_IDX_BATCH_MONITOR_JOB_DEF
  ON ACT_RU_BATCH (MONITOR_JOB_DEF_ID_)
/

CREATE TABLE ACT_HI_PROCINST
(
    ID_                        NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    PROC_INST_ID_              NVARCHAR2(64) NOT NULL
        UNIQUE,
    BUSINESS_KEY_              NVARCHAR2(255),
    PROC_DEF_KEY_              NVARCHAR2(255),
    PROC_DEF_ID_               NVARCHAR2(64) NOT NULL,
    START_TIME_                TIMESTAMP(6) NOT NULL,
    END_TIME_                  TIMESTAMP(6),
    REMOVAL_TIME_              TIMESTAMP(6),
    DURATION_                  NUMBER(19),
    START_USER_ID_             NVARCHAR2(255),
    START_ACT_ID_              NVARCHAR2(255),
    END_ACT_ID_                NVARCHAR2(255),
    SUPER_PROCESS_INSTANCE_ID_ NVARCHAR2(64),
    ROOT_PROC_INST_ID_         NVARCHAR2(64),
    SUPER_CASE_INSTANCE_ID_    NVARCHAR2(64),
    CASE_INST_ID_              NVARCHAR2(64),
    DELETE_REASON_             NVARCHAR2(2000),
    TENANT_ID_                 NVARCHAR2(64),
    STATE_                     NVARCHAR2(255)
)
    /

CREATE
INDEX ACT_IDX_HI_PRO_I_BUSKEY
  ON ACT_HI_PROCINST (BUSINESS_KEY_)
/

CREATE
INDEX ACT_IDX_HI_PRO_INST_PROC_KEY
  ON ACT_HI_PROCINST (PROC_DEF_KEY_)
/

CREATE
INDEX ACT_IDX_HI_PI_PDEFID_END_TIME
  ON ACT_HI_PROCINST (PROC_DEF_ID_, END_TIME_)
/

CREATE
INDEX ACT_IDX_HI_PRO_INST_PROC_TIME
  ON ACT_HI_PROCINST (START_TIME_, END_TIME_)
/

CREATE
INDEX ACT_IDX_HI_PRO_INST_END
  ON ACT_HI_PROCINST (END_TIME_)
/

CREATE
INDEX ACT_IDX_HI_PRO_INST_RM_TIME
  ON ACT_HI_PROCINST (REMOVAL_TIME_)
/

CREATE
INDEX ACT_IDX_HI_PRO_INST_ROOT_PI
  ON ACT_HI_PROCINST (ROOT_PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_PRO_INST_TENANT_ID
  ON ACT_HI_PROCINST (TENANT_ID_, 0)
/

CREATE TABLE ACT_HI_ACTINST
(
    ID_                 NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    PARENT_ACT_INST_ID_ NVARCHAR2(64),
    PROC_DEF_KEY_       NVARCHAR2(255),
    PROC_DEF_ID_        NVARCHAR2(64) NOT NULL,
    ROOT_PROC_INST_ID_  NVARCHAR2(64),
    PROC_INST_ID_       NVARCHAR2(64) NOT NULL,
    EXECUTION_ID_       NVARCHAR2(64) NOT NULL,
    ACT_ID_             NVARCHAR2(255) NOT NULL,
    TASK_ID_            NVARCHAR2(64),
    CALL_PROC_INST_ID_  NVARCHAR2(64),
    CALL_CASE_INST_ID_  NVARCHAR2(64),
    ACT_NAME_           NVARCHAR2(255),
    ACT_TYPE_           NVARCHAR2(255) NOT NULL,
    ASSIGNEE_           NVARCHAR2(64),
    START_TIME_         TIMESTAMP(6) NOT NULL,
    END_TIME_           TIMESTAMP(6),
    DURATION_           NUMBER(19),
    ACT_INST_STATE_     NUMBER,
    SEQUENCE_COUNTER_   NUMBER(19),
    TENANT_ID_          NVARCHAR2(64),
    REMOVAL_TIME_       TIMESTAMP(6)
)
    /

CREATE
INDEX ACT_IDX_HI_ACT_INST_PROC_KEY
  ON ACT_HI_ACTINST (PROC_DEF_KEY_)
/

CREATE
INDEX ACT_IDX_HI_ACT_INST_STATS
  ON ACT_HI_ACTINST (PROC_DEF_ID_, PROC_INST_ID_, ACT_ID_, END_TIME_, ACT_INST_STATE_)
/

CREATE
INDEX ACT_IDX_HI_AI_PDEFID_END_TIME
  ON ACT_HI_ACTINST (PROC_DEF_ID_, END_TIME_)
/

CREATE
INDEX ACT_IDX_HI_ACTINST_ROOT_PI
  ON ACT_HI_ACTINST (ROOT_PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_ACT_INST_PROCINST
  ON ACT_HI_ACTINST (PROC_INST_ID_, ACT_ID_)
/

CREATE
INDEX ACT_IDX_HI_ACT_INST_COMP
  ON ACT_HI_ACTINST (EXECUTION_ID_, ACT_ID_, END_TIME_, ID_)
/

CREATE
INDEX ACT_IDX_HI_ACT_INST_START
  ON ACT_HI_ACTINST (START_TIME_)
/

CREATE
INDEX ACT_IDX_HI_ACT_INST_END
  ON ACT_HI_ACTINST (END_TIME_)
/

CREATE
INDEX ACT_IDX_HI_ACT_INST_TENANT_ID
  ON ACT_HI_ACTINST (TENANT_ID_, 0)
/

CREATE
INDEX ACT_IDX_HI_ACT_INST_RM_TIME
  ON ACT_HI_ACTINST (REMOVAL_TIME_)
/

CREATE TABLE ACT_HI_TASKINST
(
    ID_                NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    TASK_DEF_KEY_      NVARCHAR2(255),
    PROC_DEF_KEY_      NVARCHAR2(255),
    PROC_DEF_ID_       NVARCHAR2(64),
    ROOT_PROC_INST_ID_ NVARCHAR2(64),
    PROC_INST_ID_      NVARCHAR2(64),
    EXECUTION_ID_      NVARCHAR2(64),
    CASE_DEF_KEY_      NVARCHAR2(255),
    CASE_DEF_ID_       NVARCHAR2(64),
    CASE_INST_ID_      NVARCHAR2(64),
    CASE_EXECUTION_ID_ NVARCHAR2(64),
    ACT_INST_ID_       NVARCHAR2(64),
    PARENT_TASK_ID_    NVARCHAR2(64),
    NAME_              NVARCHAR2(255),
    DESCRIPTION_       NVARCHAR2(2000),
    OWNER_             NVARCHAR2(255),
    ASSIGNEE_          NVARCHAR2(255),
    START_TIME_        TIMESTAMP(6) NOT NULL,
    END_TIME_          TIMESTAMP(6),
    DURATION_          NUMBER(19),
    DELETE_REASON_     NVARCHAR2(2000),
    PRIORITY_          NUMBER,
    DUE_DATE_          TIMESTAMP(6),
    FOLLOW_UP_DATE_    TIMESTAMP(6),
    TENANT_ID_         NVARCHAR2(64),
    REMOVAL_TIME_      TIMESTAMP(6)
)
    /

CREATE
INDEX ACT_IDX_HI_TASKINSTID_PROCINST
  ON ACT_HI_TASKINST (ID_, PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_TASK_INST_PROC_KEY
  ON ACT_HI_TASKINST (PROC_DEF_KEY_)
/

CREATE
INDEX ACT_IDX_HI_TASKINST_ROOT_PI
  ON ACT_HI_TASKINST (ROOT_PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_TASKINST_PROCINST
  ON ACT_HI_TASKINST (PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_TASK_INST_START
  ON ACT_HI_TASKINST (START_TIME_)
/

CREATE
INDEX ACT_IDX_HI_TASK_INST_END
  ON ACT_HI_TASKINST (END_TIME_)
/

CREATE
INDEX ACT_IDX_HI_TASK_INST_TENANT_ID
  ON ACT_HI_TASKINST (TENANT_ID_, 0)
/

CREATE
INDEX ACT_IDX_HI_TASK_INST_RM_TIME
  ON ACT_HI_TASKINST (REMOVAL_TIME_)
/

CREATE TABLE ACT_HI_VARINST
(
    ID_                NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    PROC_DEF_KEY_      NVARCHAR2(255),
    PROC_DEF_ID_       NVARCHAR2(64),
    ROOT_PROC_INST_ID_ NVARCHAR2(64),
    PROC_INST_ID_      NVARCHAR2(64),
    EXECUTION_ID_      NVARCHAR2(64),
    ACT_INST_ID_       NVARCHAR2(64),
    CASE_DEF_KEY_      NVARCHAR2(255),
    CASE_DEF_ID_       NVARCHAR2(64),
    CASE_INST_ID_      NVARCHAR2(64),
    CASE_EXECUTION_ID_ NVARCHAR2(64),
    TASK_ID_           NVARCHAR2(64),
    NAME_              NVARCHAR2(255) NOT NULL,
    VAR_TYPE_          NVARCHAR2(100),
    CREATE_TIME_       TIMESTAMP(6),
    REV_               NUMBER,
    BYTEARRAY_ID_      NVARCHAR2(64),
    DOUBLE_            NUMBER(*, 10),
    LONG_              NUMBER(19),
    TEXT_              NVARCHAR2(2000),
    TEXT2_             NVARCHAR2(2000),
    TENANT_ID_         NVARCHAR2(64),
    STATE_             NVARCHAR2(20),
    REMOVAL_TIME_      TIMESTAMP(6)
)
    /

CREATE
INDEX ACT_IDX_HI_VAR_INST_PROC_KEY
  ON ACT_HI_VARINST (PROC_DEF_KEY_)
/

CREATE
INDEX ACT_IDX_HI_VARINST_ROOT_PI
  ON ACT_HI_VARINST (ROOT_PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_PROCVAR_PROC_INST
  ON ACT_HI_VARINST (PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_CASEVAR_CASE_INST
  ON ACT_HI_VARINST (CASE_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_PROCVAR_NAME_TYPE
  ON ACT_HI_VARINST (NAME_, VAR_TYPE_)
/

CREATE
INDEX ACT_IDX_HI_VARINST_BYTEAR
  ON ACT_HI_VARINST (BYTEARRAY_ID_)
/

CREATE
INDEX ACT_IDX_HI_VAR_INST_TENANT_ID
  ON ACT_HI_VARINST (TENANT_ID_, 0)
/

CREATE
INDEX ACT_IDX_HI_VARINST_RM_TIME
  ON ACT_HI_VARINST (REMOVAL_TIME_)
/

CREATE TABLE ACT_HI_DETAIL
(
    ID_                NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    TYPE_              NVARCHAR2(255) NOT NULL,
    PROC_DEF_KEY_      NVARCHAR2(255),
    PROC_DEF_ID_       NVARCHAR2(64),
    ROOT_PROC_INST_ID_ NVARCHAR2(64),
    PROC_INST_ID_      NVARCHAR2(64),
    EXECUTION_ID_      NVARCHAR2(64),
    CASE_DEF_KEY_      NVARCHAR2(255),
    CASE_DEF_ID_       NVARCHAR2(64),
    CASE_INST_ID_      NVARCHAR2(64),
    CASE_EXECUTION_ID_ NVARCHAR2(64),
    TASK_ID_           NVARCHAR2(64),
    ACT_INST_ID_       NVARCHAR2(64),
    VAR_INST_ID_       NVARCHAR2(64),
    NAME_              NVARCHAR2(255) NOT NULL,
    VAR_TYPE_          NVARCHAR2(64),
    REV_               NUMBER,
    TIME_              TIMESTAMP(6) NOT NULL,
    BYTEARRAY_ID_      NVARCHAR2(64),
    DOUBLE_            NUMBER(*, 10),
    LONG_              NUMBER(19),
    TEXT_              NVARCHAR2(2000),
    TEXT2_             NVARCHAR2(2000),
    SEQUENCE_COUNTER_  NUMBER(19),
    TENANT_ID_         NVARCHAR2(64),
    OPERATION_ID_      NVARCHAR2(64),
    REMOVAL_TIME_      TIMESTAMP(6)
)
    /

CREATE
INDEX ACT_IDX_HI_DETAIL_PROC_KEY
  ON ACT_HI_DETAIL (PROC_DEF_KEY_)
/

CREATE
INDEX ACT_IDX_HI_DETAIL_ROOT_PI
  ON ACT_HI_DETAIL (ROOT_PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_DETAIL_PROC_INST
  ON ACT_HI_DETAIL (PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_DETAIL_CASE_INST
  ON ACT_HI_DETAIL (CASE_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_DETAIL_CASE_EXEC
  ON ACT_HI_DETAIL (CASE_EXECUTION_ID_)
/

CREATE
INDEX ACT_IDX_HI_DETAIL_TASK_ID
  ON ACT_HI_DETAIL (TASK_ID_)
/

CREATE
INDEX ACT_IDX_HI_DETAIL_ACT_INST
  ON ACT_HI_DETAIL (ACT_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_DETAIL_NAME
  ON ACT_HI_DETAIL (NAME_)
/

CREATE
INDEX ACT_IDX_HI_DETAIL_TIME
  ON ACT_HI_DETAIL (TIME_)
/

CREATE
INDEX ACT_IDX_HI_DETAIL_TASK_BYTEAR
  ON ACT_HI_DETAIL (BYTEARRAY_ID_, TASK_ID_)
/

CREATE
INDEX ACT_IDX_HI_DETAIL_BYTEAR
  ON ACT_HI_DETAIL (BYTEARRAY_ID_)
/

CREATE
INDEX ACT_IDX_HI_DETAIL_TENANT_ID
  ON ACT_HI_DETAIL (TENANT_ID_, 0)
/

CREATE
INDEX ACT_IDX_HI_DETAIL_RM_TIME
  ON ACT_HI_DETAIL (REMOVAL_TIME_)
/

CREATE TABLE ACT_HI_IDENTITYLINK
(
    ID_                NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    TIMESTAMP_         TIMESTAMP(6) NOT NULL,
    TYPE_              NVARCHAR2(255),
    USER_ID_           NVARCHAR2(255),
    GROUP_ID_          NVARCHAR2(255),
    TASK_ID_           NVARCHAR2(64),
    ROOT_PROC_INST_ID_ NVARCHAR2(64),
    PROC_DEF_ID_       NVARCHAR2(64),
    OPERATION_TYPE_    NVARCHAR2(64),
    ASSIGNER_ID_       NVARCHAR2(64),
    PROC_DEF_KEY_      NVARCHAR2(255),
    TENANT_ID_         NVARCHAR2(64),
    REMOVAL_TIME_      TIMESTAMP(6)
)
    /

CREATE
INDEX ACT_IDX_HI_IDENT_LNK_USER
  ON ACT_HI_IDENTITYLINK (USER_ID_)
/

CREATE
INDEX ACT_IDX_HI_IDENT_LNK_GROUP
  ON ACT_HI_IDENTITYLINK (GROUP_ID_)
/

CREATE
INDEX ACT_IDX_HI_IDENT_LINK_TASK
  ON ACT_HI_IDENTITYLINK (TASK_ID_)
/

CREATE
INDEX ACT_IDX_HI_IDENT_LNK_ROOT_PI
  ON ACT_HI_IDENTITYLINK (ROOT_PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_IDENT_LNK_PROC_KEY
  ON ACT_HI_IDENTITYLINK (PROC_DEF_KEY_)
/

CREATE
INDEX ACT_IDX_HI_IDENT_LNK_TENANT_ID
  ON ACT_HI_IDENTITYLINK (TENANT_ID_, 0)
/

CREATE
INDEX ACT_IDX_HI_IDENT_LINK_RM_TIME
  ON ACT_HI_IDENTITYLINK (REMOVAL_TIME_)
/

CREATE TABLE ACT_HI_COMMENT
(
    ID_                NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    TYPE_              NVARCHAR2(255),
    TIME_              TIMESTAMP(6) NOT NULL,
    USER_ID_           NVARCHAR2(255),
    TASK_ID_           NVARCHAR2(64),
    ROOT_PROC_INST_ID_ NVARCHAR2(64),
    PROC_INST_ID_      NVARCHAR2(64),
    ACTION_            NVARCHAR2(255),
    MESSAGE_           NVARCHAR2(2000),
    FULL_MSG_          BLOB,
    TENANT_ID_         NVARCHAR2(64),
    REMOVAL_TIME_      TIMESTAMP(6)
)
    /

CREATE
INDEX ACT_IDX_HI_COMMENT_TASK
  ON ACT_HI_COMMENT (TASK_ID_)
/

CREATE
INDEX ACT_IDX_HI_COMMENT_ROOT_PI
  ON ACT_HI_COMMENT (ROOT_PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_COMMENT_PROCINST
  ON ACT_HI_COMMENT (PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_COMMENT_RM_TIME
  ON ACT_HI_COMMENT (REMOVAL_TIME_)
/

CREATE TABLE ACT_HI_ATTACHMENT
(
    ID_                NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_               NUMBER,
    USER_ID_           NVARCHAR2(255),
    NAME_              NVARCHAR2(255),
    DESCRIPTION_       NVARCHAR2(2000),
    TYPE_              NVARCHAR2(255),
    TASK_ID_           NVARCHAR2(64),
    ROOT_PROC_INST_ID_ NVARCHAR2(64),
    PROC_INST_ID_      NVARCHAR2(64),
    URL_               NVARCHAR2(2000),
    CONTENT_ID_        NVARCHAR2(64),
    TENANT_ID_         NVARCHAR2(64),
    CREATE_TIME_       TIMESTAMP(6),
    REMOVAL_TIME_      TIMESTAMP(6)
)
    /

CREATE
INDEX ACT_IDX_HI_ATTACHMENT_TASK
  ON ACT_HI_ATTACHMENT (TASK_ID_)
/

CREATE
INDEX ACT_IDX_HI_ATTACHMENT_ROOT_PI
  ON ACT_HI_ATTACHMENT (ROOT_PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_ATTACHMENT_PROCINST
  ON ACT_HI_ATTACHMENT (PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_ATTACHMENT_CONTENT
  ON ACT_HI_ATTACHMENT (CONTENT_ID_)
/

CREATE
INDEX ACT_IDX_HI_ATTACHMENT_RM_TIME
  ON ACT_HI_ATTACHMENT (REMOVAL_TIME_)
/

CREATE TABLE ACT_HI_OP_LOG
(
    ID_                NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    DEPLOYMENT_ID_     NVARCHAR2(64),
    PROC_DEF_ID_       NVARCHAR2(64),
    PROC_DEF_KEY_      NVARCHAR2(255),
    ROOT_PROC_INST_ID_ NVARCHAR2(64),
    PROC_INST_ID_      NVARCHAR2(64),
    EXECUTION_ID_      NVARCHAR2(64),
    CASE_DEF_ID_       NVARCHAR2(64),
    CASE_INST_ID_      NVARCHAR2(64),
    CASE_EXECUTION_ID_ NVARCHAR2(64),
    TASK_ID_           NVARCHAR2(64),
    JOB_ID_            NVARCHAR2(64),
    JOB_DEF_ID_        NVARCHAR2(64),
    BATCH_ID_          NVARCHAR2(64),
    USER_ID_           NVARCHAR2(255),
    TIMESTAMP_         TIMESTAMP(6) NOT NULL,
    OPERATION_TYPE_    NVARCHAR2(255),
    OPERATION_ID_      NVARCHAR2(64),
    ENTITY_TYPE_       NVARCHAR2(30),
    PROPERTY_          NVARCHAR2(64),
    ORG_VALUE_         NVARCHAR2(2000),
    NEW_VALUE_         NVARCHAR2(2000),
    TENANT_ID_         NVARCHAR2(64),
    REMOVAL_TIME_      TIMESTAMP(6)
)
    /

CREATE
INDEX ACT_IDX_HI_OP_LOG_PROCDEF
  ON ACT_HI_OP_LOG (PROC_DEF_ID_)
/

CREATE
INDEX ACT_IDX_HI_OP_LOG_ROOT_PI
  ON ACT_HI_OP_LOG (ROOT_PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_OP_LOG_PROCINST
  ON ACT_HI_OP_LOG (PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_OP_LOG_TASK
  ON ACT_HI_OP_LOG (TASK_ID_)
/

CREATE
INDEX ACT_IDX_HI_OP_LOG_TIMESTAMP
  ON ACT_HI_OP_LOG (TIMESTAMP_)
/

CREATE
INDEX ACT_IDX_HI_OP_LOG_RM_TIME
  ON ACT_HI_OP_LOG (REMOVAL_TIME_)
/

CREATE TABLE ACT_HI_INCIDENT
(
    ID_                     NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    PROC_DEF_KEY_           NVARCHAR2(255),
    PROC_DEF_ID_            NVARCHAR2(64),
    ROOT_PROC_INST_ID_      NVARCHAR2(64),
    PROC_INST_ID_           NVARCHAR2(64),
    EXECUTION_ID_           NVARCHAR2(64),
    CREATE_TIME_            TIMESTAMP(6) NOT NULL,
    END_TIME_               TIMESTAMP(6),
    INCIDENT_MSG_           NVARCHAR2(2000),
    INCIDENT_TYPE_          NVARCHAR2(255) NOT NULL,
    ACTIVITY_ID_            NVARCHAR2(255),
    CAUSE_INCIDENT_ID_      NVARCHAR2(64),
    ROOT_CAUSE_INCIDENT_ID_ NVARCHAR2(64),
    CONFIGURATION_          NVARCHAR2(255),
    INCIDENT_STATE_         NUMBER,
    TENANT_ID_              NVARCHAR2(64),
    JOB_DEF_ID_             NVARCHAR2(64),
    REMOVAL_TIME_           TIMESTAMP(6)
)
    /

CREATE
INDEX ACT_IDX_HI_INCIDENT_PROC_KEY
  ON ACT_HI_INCIDENT (PROC_DEF_KEY_)
/

CREATE
INDEX ACT_IDX_HI_INCIDENT_ROOT_PI
  ON ACT_HI_INCIDENT (ROOT_PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_INCIDENT_PROCINST
  ON ACT_HI_INCIDENT (PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_INCIDENT_TENANT_ID
  ON ACT_HI_INCIDENT (TENANT_ID_, 0)
/

CREATE
INDEX ACT_IDX_HI_INCIDENT_RM_TIME
  ON ACT_HI_INCIDENT (REMOVAL_TIME_)
/

CREATE TABLE ACT_HI_JOB_LOG
(
    ID_                     NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    TIMESTAMP_              TIMESTAMP(6) NOT NULL,
    JOB_ID_                 NVARCHAR2(64) NOT NULL,
    JOB_DUEDATE_            TIMESTAMP(6),
    JOB_RETRIES_            NUMBER,
    JOB_PRIORITY_           NUMBER(19) DEFAULT 0 NOT NULL,
    JOB_EXCEPTION_MSG_      NVARCHAR2(2000),
    JOB_EXCEPTION_STACK_ID_ NVARCHAR2(64),
    JOB_STATE_              NUMBER,
    JOB_DEF_ID_             NVARCHAR2(64),
    JOB_DEF_TYPE_           NVARCHAR2(255),
    JOB_DEF_CONFIGURATION_  NVARCHAR2(255),
    ACT_ID_                 NVARCHAR2(255),
    EXECUTION_ID_           NVARCHAR2(64),
    ROOT_PROC_INST_ID_      NVARCHAR2(64),
    PROCESS_INSTANCE_ID_    NVARCHAR2(64),
    PROCESS_DEF_ID_         NVARCHAR2(64),
    PROCESS_DEF_KEY_        NVARCHAR2(255),
    DEPLOYMENT_ID_          NVARCHAR2(64),
    SEQUENCE_COUNTER_       NUMBER(19),
    TENANT_ID_              NVARCHAR2(64),
    REMOVAL_TIME_           TIMESTAMP(6)
)
    /

CREATE
INDEX ACT_IDX_HI_JOB_LOG_EX_STACK
  ON ACT_HI_JOB_LOG (JOB_EXCEPTION_STACK_ID_)
/

CREATE
INDEX ACT_IDX_HI_JOB_LOG_JOB_DEF_ID
  ON ACT_HI_JOB_LOG (JOB_DEF_ID_)
/

CREATE
INDEX ACT_IDX_HI_JOB_LOG_ROOT_PI
  ON ACT_HI_JOB_LOG (ROOT_PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_JOB_LOG_PROCINST
  ON ACT_HI_JOB_LOG (PROCESS_INSTANCE_ID_)
/

CREATE
INDEX ACT_IDX_HI_JOB_LOG_PROCDEF
  ON ACT_HI_JOB_LOG (PROCESS_DEF_ID_)
/

CREATE
INDEX ACT_IDX_HI_JOB_LOG_PROC_KEY
  ON ACT_HI_JOB_LOG (PROCESS_DEF_KEY_)
/

CREATE
INDEX ACT_IDX_HI_JOB_LOG_TENANT_ID
  ON ACT_HI_JOB_LOG (TENANT_ID_, 0)
/

CREATE
INDEX ACT_IDX_HI_JOB_LOG_RM_TIME
  ON ACT_HI_JOB_LOG (REMOVAL_TIME_)
/

CREATE TABLE ACT_HI_BATCH
(
    ID_                  NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    TYPE_                NVARCHAR2(255),
    TOTAL_JOBS_          NUMBER,
    JOBS_PER_SEED_       NUMBER,
    INVOCATIONS_PER_JOB_ NUMBER,
    SEED_JOB_DEF_ID_     NVARCHAR2(64),
    MONITOR_JOB_DEF_ID_  NVARCHAR2(64),
    BATCH_JOB_DEF_ID_    NVARCHAR2(64),
    TENANT_ID_           NVARCHAR2(64),
    CREATE_USER_ID_      NVARCHAR2(255),
    START_TIME_          TIMESTAMP(6) NOT NULL,
    END_TIME_            TIMESTAMP(6),
    REMOVAL_TIME_        TIMESTAMP(6)
)
    /

CREATE
INDEX ACT_HI_BAT_RM_TIME
  ON ACT_HI_BATCH (REMOVAL_TIME_)
/

CREATE TABLE ACT_HI_EXT_TASK_LOG
(
    ID_                NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    TIMESTAMP_         TIMESTAMP(6) NOT NULL,
    EXT_TASK_ID_       NVARCHAR2(64) NOT NULL,
    RETRIES_           NUMBER,
    TOPIC_NAME_        NVARCHAR2(255),
    WORKER_ID_         NVARCHAR2(255),
    PRIORITY_          NUMBER(19) DEFAULT 0 NOT NULL,
    ERROR_MSG_         NVARCHAR2(2000),
    ERROR_DETAILS_ID_  NVARCHAR2(64),
    ACT_ID_            NVARCHAR2(255),
    ACT_INST_ID_       NVARCHAR2(64),
    EXECUTION_ID_      NVARCHAR2(64),
    ROOT_PROC_INST_ID_ NVARCHAR2(64),
    PROC_INST_ID_      NVARCHAR2(64),
    PROC_DEF_ID_       NVARCHAR2(64),
    PROC_DEF_KEY_      NVARCHAR2(255),
    TENANT_ID_         NVARCHAR2(64),
    STATE_             NUMBER,
    REMOVAL_TIME_      TIMESTAMP(6)
)
    /

CREATE
INDEX ACT_IDX_HI_EXTTASKLOG_ERRORDET
  ON ACT_HI_EXT_TASK_LOG (ERROR_DETAILS_ID_)
/

CREATE
INDEX ACT_HI_EXT_TASK_LOG_ROOT_PI
  ON ACT_HI_EXT_TASK_LOG (ROOT_PROC_INST_ID_)
/

CREATE
INDEX ACT_HI_EXT_TASK_LOG_PROCINST
  ON ACT_HI_EXT_TASK_LOG (PROC_INST_ID_)
/

CREATE
INDEX ACT_HI_EXT_TASK_LOG_PROCDEF
  ON ACT_HI_EXT_TASK_LOG (PROC_DEF_ID_)
/

CREATE
INDEX ACT_HI_EXT_TASK_LOG_PROC_KEY
  ON ACT_HI_EXT_TASK_LOG (PROC_DEF_KEY_)
/

CREATE
INDEX ACT_HI_EXT_TASK_LOG_TENANT_ID
  ON ACT_HI_EXT_TASK_LOG (TENANT_ID_)
/

CREATE
INDEX ACT_HI_EXT_TASK_LOG_RM_TIME
  ON ACT_HI_EXT_TASK_LOG (REMOVAL_TIME_)
/

CREATE TABLE ACT_ID_GROUP
(
    ID_   NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_  NUMBER,
    NAME_ NVARCHAR2(255),
    TYPE_ NVARCHAR2(255)
)
    /

CREATE TABLE ACT_ID_MEMBERSHIP
(
    USER_ID_  NVARCHAR2(64) NOT NULL,
    GROUP_ID_ NVARCHAR2(64) NOT NULL
        CONSTRAINT ACT_FK_MEMB_GROUP
        REFERENCES ACT_ID_GROUP,
    PRIMARY KEY (USER_ID_, GROUP_ID_)
)
    /

CREATE
INDEX ACT_IDX_MEMB_USER
  ON ACT_ID_MEMBERSHIP (USER_ID_)
/

CREATE
INDEX ACT_IDX_MEMB_GROUP
  ON ACT_ID_MEMBERSHIP (GROUP_ID_)
/

CREATE TABLE ACT_ID_USER
(
    ID_            NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_           NUMBER,
    FIRST_         NVARCHAR2(255),
    LAST_          NVARCHAR2(255),
    EMAIL_         NVARCHAR2(255),
    PWD_           NVARCHAR2(255),
    SALT_          NVARCHAR2(255),
    LOCK_EXP_TIME_ TIMESTAMP(6),
    ATTEMPTS_      NUMBER,
    PICTURE_ID_    NVARCHAR2(64)
)
    /

ALTER TABLE ACT_ID_MEMBERSHIP
    ADD CONSTRAINT ACT_FK_MEMB_USER
        FOREIGN KEY (USER_ID_) REFERENCES ACT_ID_USER /

CREATE TABLE ACT_ID_INFO
(
    ID_        NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_       NUMBER,
    USER_ID_   NVARCHAR2(64),
    TYPE_      NVARCHAR2(64),
    KEY_       NVARCHAR2(255),
    VALUE_     NVARCHAR2(255),
    PASSWORD_  BLOB,
    PARENT_ID_ NVARCHAR2(255)
)
    /

CREATE TABLE ACT_ID_TENANT
(
    ID_   NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_  NUMBER,
    NAME_ NVARCHAR2(255)
)
    /

CREATE TABLE ACT_ID_TENANT_MEMBER
(
    ID_        NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    TENANT_ID_ NVARCHAR2(64) NOT NULL
        CONSTRAINT ACT_FK_TENANT_MEMB
        REFERENCES ACT_ID_TENANT,
    USER_ID_   NVARCHAR2(64)
        CONSTRAINT ACT_FK_TENANT_MEMB_USER
        REFERENCES ACT_ID_USER,
    GROUP_ID_  NVARCHAR2(64)
        CONSTRAINT ACT_FK_TENANT_MEMB_GROUP
        REFERENCES ACT_ID_GROUP
)
    /

CREATE
UNIQUE INDEX ACT_UNIQ_TENANT_MEMB_GROUP
  ON ACT_ID_TENANT_MEMBER (CASE WHEN "GROUP_ID_" IS NULL
    THEN NULL
                           ELSE "TENANT_ID_" END, CASE WHEN "GROUP_ID_" IS NULL
    THEN NULL
                                                  ELSE "GROUP_ID_" END)
/

CREATE
UNIQUE INDEX ACT_UNIQ_TENANT_MEMB_USER
  ON ACT_ID_TENANT_MEMBER (CASE WHEN "USER_ID_" IS NULL
    THEN NULL
                           ELSE "TENANT_ID_" END, CASE WHEN "USER_ID_" IS NULL
    THEN NULL
                                                  ELSE "USER_ID_" END)
/

CREATE
INDEX ACT_IDX_TENANT_MEMB
  ON ACT_ID_TENANT_MEMBER (TENANT_ID_)
/

CREATE
INDEX ACT_IDX_TENANT_MEMB_USER
  ON ACT_ID_TENANT_MEMBER (USER_ID_)
/

CREATE
INDEX ACT_IDX_TENANT_MEMB_GROUP
  ON ACT_ID_TENANT_MEMBER (GROUP_ID_)
/

CREATE TABLE ACT_RE_CASE_DEF
(
    ID_                 NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_                NUMBER,
    CATEGORY_           NVARCHAR2(255),
    NAME_               NVARCHAR2(255),
    KEY_                NVARCHAR2(255) NOT NULL,
    VERSION_            NUMBER NOT NULL,
    DEPLOYMENT_ID_      NVARCHAR2(64),
    RESOURCE_NAME_      NVARCHAR2(2000),
    DGRM_RESOURCE_NAME_ NVARCHAR2(2000),
    TENANT_ID_          NVARCHAR2(64),
    HISTORY_TTL_        NUMBER
)
    /

CREATE
INDEX ACT_IDX_CASE_DEF_TENANT_ID
  ON ACT_RE_CASE_DEF (TENANT_ID_, 0)
/

ALTER TABLE ACT_RU_TASK
    ADD CONSTRAINT ACT_FK_TASK_CASE_DEF
        FOREIGN KEY (CASE_DEF_ID_) REFERENCES ACT_RE_CASE_DEF /

CREATE TABLE ACT_RU_CASE_EXECUTION
(
    ID_              NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_             NUMBER,
    CASE_INST_ID_    NVARCHAR2(64)
        CONSTRAINT ACT_FK_CASE_EXE_CASE_INST
        REFERENCES ACT_RU_CASE_EXECUTION,
    SUPER_CASE_EXEC_ NVARCHAR2(64),
    SUPER_EXEC_      NVARCHAR2(64),
    BUSINESS_KEY_    NVARCHAR2(255),
    PARENT_ID_       NVARCHAR2(64)
        CONSTRAINT ACT_FK_CASE_EXE_PARENT
        REFERENCES ACT_RU_CASE_EXECUTION,
    CASE_DEF_ID_     NVARCHAR2(64)
        CONSTRAINT ACT_FK_CASE_EXE_CASE_DEF
        REFERENCES ACT_RE_CASE_DEF,
    ACT_ID_          NVARCHAR2(255),
    PREV_STATE_      NUMBER,
    CURRENT_STATE_   NUMBER,
    REQUIRED_        NUMBER(1)
        CHECK (REQUIRED_ IN (1, 0)),
    TENANT_ID_       NVARCHAR2(64)
)
    /

CREATE
INDEX ACT_IDX_CASE_EXE_CASE_INST
  ON ACT_RU_CASE_EXECUTION (CASE_INST_ID_)
/

CREATE
INDEX ACT_IDX_CASE_EXEC_BUSKEY
  ON ACT_RU_CASE_EXECUTION (BUSINESS_KEY_)
/

CREATE
INDEX ACT_IDX_CASE_EXE_PARENT
  ON ACT_RU_CASE_EXECUTION (PARENT_ID_)
/

CREATE
INDEX ACT_IDX_CASE_EXE_CASE_DEF
  ON ACT_RU_CASE_EXECUTION (CASE_DEF_ID_)
/

CREATE
INDEX ACT_IDX_CASE_EXEC_TENANT_ID
  ON ACT_RU_CASE_EXECUTION (TENANT_ID_, 0)
/

ALTER TABLE ACT_RU_TASK
    ADD CONSTRAINT ACT_FK_TASK_CASE_EXE
        FOREIGN KEY (CASE_EXECUTION_ID_) REFERENCES ACT_RU_CASE_EXECUTION /

ALTER TABLE ACT_RU_VARIABLE
    ADD CONSTRAINT ACT_FK_VAR_CASE_EXE
        FOREIGN KEY (CASE_EXECUTION_ID_) REFERENCES ACT_RU_CASE_EXECUTION /

ALTER TABLE ACT_RU_VARIABLE
    ADD CONSTRAINT ACT_FK_VAR_CASE_INST
        FOREIGN KEY (CASE_INST_ID_) REFERENCES ACT_RU_CASE_EXECUTION /

CREATE TABLE ACT_RU_CASE_SENTRY_PART
(
    ID_                  NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_                 NUMBER,
    CASE_INST_ID_        NVARCHAR2(64)
        CONSTRAINT ACT_FK_CASE_SENTRY_CASE_INST
        REFERENCES ACT_RU_CASE_EXECUTION,
    CASE_EXEC_ID_        NVARCHAR2(64)
        CONSTRAINT ACT_FK_CASE_SENTRY_CASE_EXEC
        REFERENCES ACT_RU_CASE_EXECUTION,
    SENTRY_ID_           NVARCHAR2(255),
    TYPE_                NVARCHAR2(255),
    SOURCE_CASE_EXEC_ID_ NVARCHAR2(64),
    STANDARD_EVENT_      NVARCHAR2(255),
    SOURCE_              NVARCHAR2(255),
    VARIABLE_EVENT_      NVARCHAR2(255),
    VARIABLE_NAME_       NVARCHAR2(255),
    SATISFIED_           NUMBER(1)
        CHECK (SATISFIED_ IN (1, 0)),
    TENANT_ID_           NVARCHAR2(64)
)
    /

CREATE
INDEX ACT_IDX_CASE_SENTRY_CASE_INST
  ON ACT_RU_CASE_SENTRY_PART (CASE_INST_ID_)
/

CREATE
INDEX ACT_IDX_CASE_SENTRY_CASE_EXEC
  ON ACT_RU_CASE_SENTRY_PART (CASE_EXEC_ID_)
/

CREATE TABLE ACT_HI_CASEINST
(
    ID_                        NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    CASE_INST_ID_              NVARCHAR2(64) NOT NULL
        UNIQUE,
    BUSINESS_KEY_              NVARCHAR2(255),
    CASE_DEF_ID_               NVARCHAR2(64) NOT NULL,
    CREATE_TIME_               TIMESTAMP(6) NOT NULL,
    CLOSE_TIME_                TIMESTAMP(6),
    DURATION_                  NUMBER(19),
    STATE_                     NUMBER,
    CREATE_USER_ID_            NVARCHAR2(255),
    SUPER_CASE_INSTANCE_ID_    NVARCHAR2(64),
    SUPER_PROCESS_INSTANCE_ID_ NVARCHAR2(64),
    TENANT_ID_                 NVARCHAR2(64)
)
    /

CREATE
INDEX ACT_IDX_HI_CAS_I_BUSKEY
  ON ACT_HI_CASEINST (BUSINESS_KEY_)
/

CREATE
INDEX ACT_IDX_HI_CAS_I_CLOSE
  ON ACT_HI_CASEINST (CLOSE_TIME_)
/

CREATE
INDEX ACT_IDX_HI_CAS_I_TENANT_ID
  ON ACT_HI_CASEINST (TENANT_ID_, 0)
/

CREATE TABLE ACT_HI_CASEACTINST
(
    ID_                 NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    PARENT_ACT_INST_ID_ NVARCHAR2(64),
    CASE_DEF_ID_        NVARCHAR2(64) NOT NULL,
    CASE_INST_ID_       NVARCHAR2(64) NOT NULL,
    CASE_ACT_ID_        NVARCHAR2(255) NOT NULL,
    TASK_ID_            NVARCHAR2(64),
    CALL_PROC_INST_ID_  NVARCHAR2(64),
    CALL_CASE_INST_ID_  NVARCHAR2(64),
    CASE_ACT_NAME_      NVARCHAR2(255),
    CASE_ACT_TYPE_      NVARCHAR2(255),
    CREATE_TIME_        TIMESTAMP(6) NOT NULL,
    END_TIME_           TIMESTAMP(6),
    DURATION_           NUMBER(19),
    STATE_              NUMBER,
    REQUIRED_           NUMBER(1)
        CHECK (REQUIRED_ IN (1, 0)),
    TENANT_ID_          NVARCHAR2(64)
)
    /

CREATE
INDEX ACT_IDX_HI_CAS_A_I_COMP
  ON ACT_HI_CASEACTINST (CASE_ACT_ID_, END_TIME_, ID_)
/

CREATE
INDEX ACT_IDX_HI_CAS_A_I_CREATE
  ON ACT_HI_CASEACTINST (CREATE_TIME_)
/

CREATE
INDEX ACT_IDX_HI_CAS_A_I_END
  ON ACT_HI_CASEACTINST (END_TIME_)
/

CREATE
INDEX ACT_IDX_HI_CAS_A_I_TENANT_ID
  ON ACT_HI_CASEACTINST (TENANT_ID_, 0)
/

CREATE TABLE ACT_RE_DECISION_DEF
(
    ID_                 NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_                NUMBER,
    CATEGORY_           NVARCHAR2(255),
    NAME_               NVARCHAR2(255),
    KEY_                NVARCHAR2(255) NOT NULL,
    VERSION_            NUMBER NOT NULL,
    DEPLOYMENT_ID_      NVARCHAR2(64),
    RESOURCE_NAME_      NVARCHAR2(2000),
    DGRM_RESOURCE_NAME_ NVARCHAR2(2000),
    DEC_REQ_ID_         NVARCHAR2(64),
    DEC_REQ_KEY_        NVARCHAR2(255),
    TENANT_ID_          NVARCHAR2(64),
    HISTORY_TTL_        NUMBER,
    VERSION_TAG_        NVARCHAR2(64)
)
    /

CREATE
INDEX ACT_IDX_DEC_DEF_REQ_ID
  ON ACT_RE_DECISION_DEF (DEC_REQ_ID_)
/

CREATE
INDEX ACT_IDX_DEC_DEF_TENANT_ID
  ON ACT_RE_DECISION_DEF (TENANT_ID_, 0)
/

CREATE TABLE ACT_RE_DECISION_REQ_DEF
(
    ID_                 NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    REV_                NUMBER,
    CATEGORY_           NVARCHAR2(255),
    NAME_               NVARCHAR2(255),
    KEY_                NVARCHAR2(255) NOT NULL,
    VERSION_            NUMBER NOT NULL,
    DEPLOYMENT_ID_      NVARCHAR2(64),
    RESOURCE_NAME_      NVARCHAR2(2000),
    DGRM_RESOURCE_NAME_ NVARCHAR2(2000),
    TENANT_ID_          NVARCHAR2(64)
)
    /

CREATE
INDEX ACT_IDX_DEC_REQ_DEF_TENANT_ID
  ON ACT_RE_DECISION_REQ_DEF (TENANT_ID_, 0)
/

ALTER TABLE ACT_RE_DECISION_DEF
    ADD CONSTRAINT ACT_FK_DEC_REQ
        FOREIGN KEY (DEC_REQ_ID_) REFERENCES ACT_RE_DECISION_REQ_DEF /

CREATE TABLE ACT_HI_DECINST
(
    ID_                NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    DEC_DEF_ID_        NVARCHAR2(64) NOT NULL,
    DEC_DEF_KEY_       NVARCHAR2(255) NOT NULL,
    DEC_DEF_NAME_      NVARCHAR2(255),
    PROC_DEF_KEY_      NVARCHAR2(255),
    PROC_DEF_ID_       NVARCHAR2(64),
    PROC_INST_ID_      NVARCHAR2(64),
    CASE_DEF_KEY_      NVARCHAR2(255),
    CASE_DEF_ID_       NVARCHAR2(64),
    CASE_INST_ID_      NVARCHAR2(64),
    ACT_INST_ID_       NVARCHAR2(64),
    ACT_ID_            NVARCHAR2(255),
    EVAL_TIME_         TIMESTAMP(6) NOT NULL,
    REMOVAL_TIME_      TIMESTAMP(6),
    COLLECT_VALUE_     NUMBER(*, 10),
    USER_ID_           NVARCHAR2(255),
    ROOT_DEC_INST_ID_  NVARCHAR2(64),
    ROOT_PROC_INST_ID_ NVARCHAR2(64),
    DEC_REQ_ID_        NVARCHAR2(64),
    DEC_REQ_KEY_       NVARCHAR2(255),
    TENANT_ID_         NVARCHAR2(64)
)
    /

CREATE
INDEX ACT_IDX_HI_DEC_INST_ID
  ON ACT_HI_DECINST (DEC_DEF_ID_)
/

CREATE
INDEX ACT_IDX_HI_DEC_INST_KEY
  ON ACT_HI_DECINST (DEC_DEF_KEY_)
/

CREATE
INDEX ACT_IDX_HI_DEC_INST_PI
  ON ACT_HI_DECINST (PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_DEC_INST_CI
  ON ACT_HI_DECINST (CASE_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_DEC_INST_ACT_INST
  ON ACT_HI_DECINST (ACT_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_DEC_INST_ACT
  ON ACT_HI_DECINST (ACT_ID_)
/

CREATE
INDEX ACT_IDX_HI_DEC_INST_TIME
  ON ACT_HI_DECINST (EVAL_TIME_)
/

CREATE
INDEX ACT_IDX_HI_DEC_INST_RM_TIME
  ON ACT_HI_DECINST (REMOVAL_TIME_)
/

CREATE
INDEX ACT_IDX_HI_DEC_INST_ROOT_ID
  ON ACT_HI_DECINST (ROOT_DEC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_DEC_INST_ROOT_PI
  ON ACT_HI_DECINST (ROOT_PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_DEC_INST_REQ_ID
  ON ACT_HI_DECINST (DEC_REQ_ID_)
/

CREATE
INDEX ACT_IDX_HI_DEC_INST_REQ_KEY
  ON ACT_HI_DECINST (DEC_REQ_KEY_)
/

CREATE
INDEX ACT_IDX_HI_DEC_INST_TENANT_ID
  ON ACT_HI_DECINST (TENANT_ID_, 0)
/

CREATE TABLE ACT_HI_DEC_IN
(
    ID_                NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    DEC_INST_ID_       NVARCHAR2(64) NOT NULL,
    CLAUSE_ID_         NVARCHAR2(64),
    CLAUSE_NAME_       NVARCHAR2(255),
    VAR_TYPE_          NVARCHAR2(100),
    BYTEARRAY_ID_      NVARCHAR2(64),
    DOUBLE_            NUMBER(*, 10),
    LONG_              NUMBER(19),
    TEXT_              NVARCHAR2(2000),
    TEXT2_             NVARCHAR2(2000),
    TENANT_ID_         NVARCHAR2(64),
    CREATE_TIME_       TIMESTAMP(6),
    ROOT_PROC_INST_ID_ VARCHAR2(64),
    REMOVAL_TIME_      TIMESTAMP(6)
)
    /

CREATE
INDEX ACT_IDX_HI_DEC_IN_CLAUSE
  ON ACT_HI_DEC_IN (DEC_INST_ID_, CLAUSE_ID_)
/

CREATE
INDEX ACT_IDX_HI_DEC_IN_INST
  ON ACT_HI_DEC_IN (DEC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_DEC_IN_ROOT_PI
  ON ACT_HI_DEC_IN (ROOT_PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_DEC_IN_RM_TIME
  ON ACT_HI_DEC_IN (REMOVAL_TIME_)
/

CREATE TABLE ACT_HI_DEC_OUT
(
    ID_                NVARCHAR2(64) NOT NULL
        PRIMARY KEY,
    DEC_INST_ID_       NVARCHAR2(64) NOT NULL,
    CLAUSE_ID_         NVARCHAR2(64),
    CLAUSE_NAME_       NVARCHAR2(255),
    RULE_ID_           NVARCHAR2(64),
    RULE_ORDER_        NUMBER,
    VAR_NAME_          NVARCHAR2(255),
    VAR_TYPE_          NVARCHAR2(100),
    BYTEARRAY_ID_      NVARCHAR2(64),
    DOUBLE_            NUMBER(*, 10),
    LONG_              NUMBER(19),
    TEXT_              NVARCHAR2(2000),
    TEXT2_             NVARCHAR2(2000),
    TENANT_ID_         NVARCHAR2(64),
    CREATE_TIME_       TIMESTAMP(6),
    ROOT_PROC_INST_ID_ VARCHAR2(64),
    REMOVAL_TIME_      TIMESTAMP(6)
)
    /

CREATE
INDEX ACT_IDX_HI_DEC_OUT_INST
  ON ACT_HI_DEC_OUT (DEC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_DEC_OUT_RULE
  ON ACT_HI_DEC_OUT (RULE_ORDER_, CLAUSE_ID_)
/

CREATE
INDEX ACT_IDX_HI_DEC_OUT_ROOT_PI
  ON ACT_HI_DEC_OUT (ROOT_PROC_INST_ID_)
/

CREATE
INDEX ACT_IDX_HI_DEC_OUT_RM_TIME
  ON ACT_HI_DEC_OUT (REMOVAL_TIME_)
/


